#!/usr/bin/env bash
# This script is used to transfer files from one server to another

if [ $# -ne 4 ]; then
    echo "Usage: $0 <source_server> <source_file> <destination_server> <destination_file>"
    exit 1
fi


PATH_TO_FILE=$1
IP_ADDRESS=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP_ADDRESS:~/"

if [ $? -eq 0 ]; then
  echo "File transfer successful"
else
  echo "File transfer failed"
fi