#!/usr/bin/env bash
# This script displays numbers from 1 to 100, but for multiples of three prints "Fizz" instead of the number, and for the multiples of five prints "Buzz". For numbers which are multiples of both three and five it prints "FizzBuzz".

for number in {1..100}
do
   if (( number % 3 == 0 && number % 5 == 0 ))
   then
       echo "FizzBuzz"
   elif (( number % 3 == 0 ))
   then
       echo "Fizz"
   elif (( number % 5 == 0 ))
   then
       echo "Buzz"
   else
       echo $number
   fi
done
