#!/usr/bin/env bash
# This script installs Apache, creates a simple HTML page, and starts the Apache service

# Update the package list
apt-get update

# Install Apache
apt-get install apache2 -y

# Ensure Apache runs on startup
systemctl enable apache2

# Create the HTML file with "Hello Holberton"
echo "Hello Holberton" > /var/www/html/index.html

# Set correct permissions for the HTML file
chmod 644 /var/www/html/index.html

# Start the Apache service
service apache2 start
